### ISSUE TITLE
知乎来的，readme开源第一人是吧

### ISSUE THREAD

**Issue by wwbs4564** [ChiCheng123/JointDet#5]
如何看待不开源代码的论文? - 知乎
https://www.zhihu.com/question/567652901/answer/2922455674

**Comment by continue-learn** [comment]
经典

**Comment by systemX1** [comment]
乐了

**Comment by snake6868** [comment]
路过

**Comment by ChiCheng123** [comment]
The code is available now. Sorry for the late release.
